format = """
[ ](fg:#ECEFF4)\
$username\
[ ](fg:#ECEFF4)\
$directory\
[](fg:#91c68f)\
$git_branch\
$git_status\
[](fg:#75a173)\
[ ](fg:#506f4f)\
$character"""

[hostname]
ssh_only = false
style = "fg:8FBCBB"
format = "[$hostname]($style)"
disabled = false
[username]
style_user = "fg:#ECEFF4"
style_root = "fg:black bold"
format = "[$user]($style)"
disabled = false
show_always = true

[character]
success_symbol = "[](bold green)"
error_symbol = "[✗](bold red)"

# DEFAULTS BELOW

[directory]
style = "fg:#e3e5e5"
format = "[ $path ]($style)"
truncation_length = 2
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
format = '[ $symbol $branch ](fg:blue bold)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
disabled = true

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
disabled = true

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
disabled = true

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
disabled = true

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
